---

- name: Back-up existing build artifact if necessary
  shell: cp -p {{ project_target_path }} {{ project_target_path }}_`date +%Y%m%d` removes={{ project_target_path }}

- name: Copy build artifact from sftp_server_name to project_target_path
  shell: >
    (
    echo "get {{ project_source_path }} {{ project_target_path }}" ;
    echo "bye"
    ) | sftp -oIdentityFile={{ ansible_ident_file }} -b - {{ sftp_username }}@{{ sftp_server_name }}:{{ sftp_path }}
  args:
    executable: /bin/bash
  register: sftp_status
  failed_when: "sftp_status.rc != 0"
  notify:
    - restart tomcatinstance
