---

- name: Back-up existing build artifact if necessary
  shell: >
    cp -p /usr/local/{{ project_name }}/webapps/{{ project_name }}.war
    /usr/local/{{ project_name }}/webapps/{{ project_name }}.war_`date +%Y%m%d%H%M%S`
    removes=/usr/local/{{ project_name }}/webapps/{{ project_name }}.war

- name: Copy build artifact from sftp_server_name to project_target_path
  shell: >
    (
    echo "get {{ project_name }}/{{ project_name }}.war /usr/local/{{ project_name }}/webapps/{{ project_name }}.war" ;
    echo "bye"
    ) | sftp -oIdentityFile={{ ansible_ident_file }} -b - {{ sftp_username }}@{{ sftp_server_name }}:{{ sftp_path }}
  args:
    executable: /bin/bash
  register: sftp_status
  failed_when: "sftp_status.rc != 0"

- name: Restart Tomcat Instances
  service: name={{ project_name }} state=restarted
